version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: [ "27017:27017" ]
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    image: ai-fitness-backend
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=ai_fitness
    ports: [ "5000:5000" ]
    depends_on: [ mongo ]

  frontend:
    working_dir: /app
    image: node:20-alpine
    command: sh -c "npm i && npm run dev -- --host"
    ports: [ "5173:5173" ]
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on: [ backend ]

volumes:
  mongo_data:
